// Bundles the icons the reels use into lib/icons.js, so a composition works from file:// with no fetches.
// Tabler icons (MIT) plus a few drawn for these reels.
import { readFileSync, writeFileSync } from 'node:fs'

const TABLER = ['sailboat', 'target', 'beer', 'steering-wheel', 'cards', 'fish-hook', 'grill', 'lock', 'ping-pong', 'circles', 'bucket-droplet', 'device-gamepad-2']
const icons = {}
for (const name of TABLER) {
  const svg = readFileSync(`node_modules/@tabler/icons/icons/outline/${name}.svg`, 'utf8')
  icons[name] = svg.replace(/<!--[\s\S]*?-->/g, '').replace(/\s*class="[^"]*"/, '').replace(/\s+/g, ' ').trim()
}

const draw = (body) => `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${body}</svg>`
icons.bull = draw('<path d="M7 8c-3 0 -4 -2 -4 -4" /><path d="M17 8c3 0 4 -2 4 -4" /><path d="M7 8h10l-1 7a4 4 0 0 1 -8 0z" /><path d="M7 9.5l-2.5 1.5" /><path d="M17 9.5l2.5 1.5" /><circle cx="12" cy="17.6" r="1.4" />')
icons['eight-ball'] = draw('<circle cx="12" cy="12" r="9" /><circle cx="12" cy="11" r="3.6" /><path d="M12 9.2a.9 .9 0 1 0 0 1.8a.9 .9 0 1 0 0 -1.8m0 1.8a1 1 0 1 0 0 2a1 1 0 1 0 0 -2" stroke-width="1.2" />')
icons.pickleball = draw('<rect x="3" y="3" width="10" height="11" rx="4" transform="rotate(-35 8 8.5)" /><path d="M11 13.5l3.5 4" /><circle cx="18" cy="18" r="3" /><circle cx="17.2" cy="17.4" r=".3" /><circle cx="18.9" cy="18.6" r=".3" />')
icons.puck = draw('<ellipse cx="12" cy="10" rx="8" ry="3" /><path d="M4 10v4c0 1.7 3.6 3 8 3s8 -1.3 8 -3v-4" /><path d="M16 5l3 -2" />')

writeFileSync('lib/icons.js', '// Generated by tools/icons.mjs. Tabler icons are MIT licensed (tabler.io/icons).\nwindow.ICONS = ' + JSON.stringify(icons, null, 1) + '\n')
console.log(Object.keys(icons).length, 'icons written to lib/icons.js')
